informationServer:
  port: 7777

# datasource
spring:
#  datasource:
#    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver

  infoserv-datasource:
    jdbcUrl: jdbc:h2:mem:infoserv;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS FIRST
    username: sa
    #password: sa
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect

  bhs-datasource:
    jdbcUrl: jdbc:h2:mem:bhs;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS FIRST
    username: sa
    #password: sa
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect

    #jdbcUrl: jdbc:oracle:thin:@//localhost:1521/DS
    #jdbcUrl: jdbc:oracle:thin:@//172.16.241.100:1521/DS
    #username: cust_access
    #password: cust_pwd
    #driver-class-name: oracle.jdbc.OracleDriver
    #hibernate:
      #dialect: org.hibernate.dialect.OracleDialect



  # h2:
#    console:
#      enabled: true
#      path: /h2-console
#http://localhost:8080/h2-console

# jpa properties
  jpa:
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        use_sql_comments: true
        #dialect: org.hibernate.dialect.OracleDialect

hibernate:
  hbm2ddl:
    auto: create-drop
  cache:
    use_second_level_cache: false
    use_query_cache: false

